apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-gateway
spec:
  selector:
    matchLabels:
      app: zuul-gateway
  template:
    metadata:
      labels:
        app: zuul-gateway
    spec:
      containers:
        - name: zuul-gateway
          image: zuul-gateway:1.0.0-SNAPSHOT
          ports:
            - containerPort: 19999
          env:
            - name: dubbo.registry.address
              value: "nacos://nacos-server:8848"
            - name: spring.cloud.nacos.discovery.server-addr
              value: "nacos-server:8848"
            - name: spring.cloud.nacos.config.server-addr
              value: "nacos-server:8848"
          # resources:
          #   requests:
          #     cpu: 100m
          #     memory: 64Mi
          #   limits:
          #     cpu: 200m
          #     memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: zuul-gateway
spec:
  type: ClusterIP
  selector:
    app: zuul-gateway
  ports:
    - name: http
      port:  8080
      targetPort:  19999
---
apiVersion: v1
kind: Service
metadata:
  name: zuul-gateway-external
spec:
  type: LoadBalancer
  selector:
    app: zuul-gateway
  ports:
    - name: http
      port:  8080
      targetPort:  19999